/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}"
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#f0f1f1",
        "surface-bright": "#f9f9f9",
        "background": "#f9f9f9",
        "surface-variant": "#e2e2e2",
        "tertiary": "#a33200",
        "surface-container-high": "#e8e8e8",
        "inverse-surface": "#2f3131",
        "on-background": "#1a1c1c",
        "on-tertiary-container": "#fff6f4",
        "on-secondary-fixed-variant": "#284386",
        "tertiary-container": "#cc4204",
        "inverse-primary": "#b3c5ff",
        "on-secondary-fixed": "#001849",
        "primary-fixed-dim": "#b3c5ff",
        "on-tertiary-fixed": "#390c00",
        "secondary-container": "#9bb4fe",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "surface": "#f9f9f9",
        "surface-container": "#eeeeee",
        "on-surface": "#1a1c1c",
        "surface-container-highest": "#e2e2e2",
        "on-primary-fixed": "#001849",
        "outline-variant": "#c2c6d8",
        "on-secondary-container": "#294487",
        "on-secondary": "#ffffff",
        "primary-container": "#0066ff",
        "on-primary-fixed-variant": "#003fa4",
        "primary": "#0050cb",
        "secondary": "#425ca0",
        "tertiary-fixed-dim": "#ffb59d",
        "on-error": "#ffffff",
        "primary-fixed": "#dae1ff",
        "secondary-fixed": "#dae1ff",
        "surface-container-low": "#f3f3f3",
        "on-tertiary-fixed-variant": "#832600",
        "secondary-fixed-dim": "#b3c5ff",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffdbd0",
        "on-primary-container": "#f8f7ff",
        "on-surface-variant": "#424656",
        "surface-tint": "#0054d6",
        "surface-dim": "#dadada",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "outline": "#727687"
      }
    },
  },
  plugins: [],
}